// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLATHvLVn7hBMm3AHahi7X5dtYFzAd5as',
    appId: '1:423837307709:web:b6ecf159f901a4dec22b54',
    messagingSenderId: '423837307709',
    projectId: 'hilo-1',
    authDomain: 'hilo-1.firebaseapp.com',
    storageBucket: 'hilo-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdc-WApsOCsheehKD_4qJEsqpGTHSq_40',
    appId: '1:423837307709:android:b00b959385ff5fd6c22b54',
    messagingSenderId: '423837307709',
    projectId: 'hilo-1',
    storageBucket: 'hilo-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbxCNc-so80E5U8Cr4g0kM-xHrezgBVs4',
    appId: '1:423837307709:ios:f05d47710fbf718bc22b54',
    messagingSenderId: '423837307709',
    projectId: 'hilo-1',
    storageBucket: 'hilo-1.firebasestorage.app',
    iosBundleId: 'com.example.hilo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbxCNc-so80E5U8Cr4g0kM-xHrezgBVs4',
    appId: '1:423837307709:ios:f05d47710fbf718bc22b54',
    messagingSenderId: '423837307709',
    projectId: 'hilo-1',
    storageBucket: 'hilo-1.firebasestorage.app',
    iosBundleId: 'com.example.hilo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLATHvLVn7hBMm3AHahi7X5dtYFzAd5as',
    appId: '1:423837307709:web:5acfcb119497f12dc22b54',
    messagingSenderId: '423837307709',
    projectId: 'hilo-1',
    authDomain: 'hilo-1.firebaseapp.com',
    storageBucket: 'hilo-1.firebasestorage.app',
  );
}